### ISSUE TITLE
Emacs 26 availability

### ISSUE THREAD

**Issue by einSelbst** [w-vi/apib-mode#7]
Hola and thanks for this. The package is not visible in the emacs package list. I see on Melpa that Emacs24 is written in the dependencies. Is it possible to allow installation on newer Emacs versions too?

**Comment by w-vi** [comment]
Hi, I'll have a look, test it and update it accordingly. Thanks for reminding me I was planning to do it for a while.

**Comment by einSelbst** [comment]
Thank you!
